const mongoose=require('mongoose');
const Schema=mongoose.Schema;


const studentSchema=new Schema({
    cin:{
        type:String,
        required:true
    },
    cne:{
        type:String,
        required:true
    },
    firstName:{
        type:String,
        required:true
    },
    lastName:{
        type:String,
        required:true
    },
    firstName_ar:{
        type:String,
        required:true
    },
    lastName_ar:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    phone:{
        type:String,
        required:true
    },
    birth_day:{
        type:Date,
        required:true
    },
    birth_place:{
        type:String,
        required:true
    },
    nationality:{
        type:String,
        required:true
    },
    father_fullName:{
        type:String,
        required:true
    },
    mother_fullName:{
        type:String,
        required:true
    },

    father_job:{
        type:String,
        required:true
    },
    mother_job:{
        type:String,
        required:true
    },
    parent_address:{
        type:String,
        required:true
    },
    parent_phone:{
        type:String,
        required:true
    },
    level:{
        type:String,
        required:true
    },
    bac_type:{
        type:String,
        required:true
    },
    bac_get_year:{
        type:Date,
        required:true
    },
    mention:{
        type:String,
        required:true
    },
    //filiere
    filiere:{
        type:Schema.Types.ObjectId,
        ref:'Filiere'
    }
    
});

module.exports=mongoose.model('Student', studentSchema);